on: [push]
name: Docker_Deploy

jobs:
    build-and-deploy: 
        runs-on: ubuntu-latest
        steps: 
        # checkout the repo
        - name: 'Checkout Github Action'
          uses: action/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
